//! Canonical tool metadata — the single source of truth for every tool.
//!
//! Before this module existed, four independent hand-maintained string lists
//! described each tool and could silently drift:
//!
//!   1. `core::tool_schemas()`          — what the model is told exists
//!   2. `policy::default_allow()`       — read-only/safe tools that skip approval
//!   3. `subagent::{READ_ONLY_TOOLS, IMPLEMENT_TOOLS, CHILD_NEVER}` — what
//!      delegated subagents may call
//!   4. `tools::dispatch`                — which calls actually execute
//!
//! Concretely, `analyze_bug`, `review_code` and `browse_web` were dispatched by
//! `tools::dispatch` (and listed by `ToolCall::name`) but never registered in
//! `tool_schemas`, so the model could never call them in agent mode — and no
//! test could catch it, because the schema map was a separate hand-written
//! `HashMap` in `core.rs`.
//!
//! This module keeps one row per tool, keyed by the exact snake_case name that
//! `ToolCall::name()` produces, with everything about the tool in one place:
//!
//!   * `schema` — the JSON schema advertised to the model (generated by
//!     [`tool_schemas`]). Every registered tool MUST have one, so the model can
//!     always reach it in agent mode.
//!   * `delegation` — how a delegated subagent may use the tool
//!     ([`SubagentAccess`]); parent agents may always call anything.
//!   * `read_only`  — the tool is safe to auto-allow (skips the approval gate
//!     unless a policy rule overrides it), returned by [`is_read_only`].
//!
//! Every consumer that used to hard-code a string list now derives it from here,
//! and [`validate()`] (called by `core::test_registry_matches_dispatcher`)
//! proves the registry names exactly match the dispatcher's `ToolCall::name()`
//! output so the two can never drift again.

use std::collections::HashMap;

use serde_json::Value;

/// How a delegated (subagent) context may use a tool.
///
/// Order matters for precedence: `ParentOnly` must always win over the others
/// (a child may never use a parent-only tool even if it also matches another
/// category), and `Implement` is additive on top of `ReadOnly`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum SubagentAccess {
    /// Available to read-only profiles (`explore`, `review`) **and** to the
    /// `implement` profile — the base set every child gets.
    ReadOnly,
    /// Available only to the `implement` profile, on top of `ReadOnly`.
    Implement,
    /// Reserved for the parent agent; no child may call it (`CHILD_NEVER`).
    ParentOnly,
    /// Not exposed to any child context at all.
    Forbidden,
}

/// One row of the canonical tool table.
#[derive(Debug, Clone, Copy)]
pub struct ToolMeta {
    /// Exact snake_case name emitted by `ToolCall::name()`.
    pub name: &'static str,
    /// Safe to auto-allow (skips the approval gate) unless overridden.
    pub read_only: bool,
    /// How subagents may use the tool.
    pub delegation: SubagentAccess,
    /// Lazily-built JSON schema advertised to the model. Required for every
    /// tool — a tool without a schema is invisible to the model.
    pub schema: fn() -> Value,
}

/// Build one read-only/read-only-profile entry (always has a schema).
const fn rw(name: &'static str, schema: fn() -> Value) -> ToolMeta {
    ToolMeta {
        name,
        read_only: true,
        delegation: SubagentAccess::ReadOnly,
        schema,
    }
}

/// Read-only but only delegated to the `implement` profile.
const fn ro_impl(name: &'static str, schema: fn() -> Value) -> ToolMeta {
    ToolMeta {
        name,
        read_only: true,
        delegation: SubagentAccess::Implement,
        schema,
    }
}

/// Read-only but forbidden to children entirely (interactive/blocking).
const fn problem(name: &'static str, schema: fn() -> Value) -> ToolMeta {
    ToolMeta {
        name,
        read_only: true,
        delegation: SubagentAccess::Forbidden,
        schema,
    }
}

/// Human-interaction tools: default-allow on the parent, never for children.
const fn parent(name: &'static str, schema: fn() -> Value) -> ToolMeta {
    ToolMeta {
        name,
        read_only: true,
        delegation: SubagentAccess::ParentOnly,
        schema,
    }
}

/// Mutating (build/write) tools: not default-allow, delegated per `delegation`.
const fn mutating(name: &'static str, delegation: SubagentAccess, schema: fn() -> Value) -> ToolMeta {
    ToolMeta {
        name,
        read_only: false,
        delegation,
        schema,
    }
}

/// The canonical tool table. Each row pairs the tool's metadata with the JSON
/// schema it advertises to the model, so dispatch, permission and schema can
/// never drift. Keep names in sync with `ToolCall::name()` —
/// [`validate()`] / [`super::core::test_registry_matches_dispatcher`] enforce it.
pub static TOOLS: &[ToolMeta] = &[
    // ---- read-only / safe (default-allow) tools --------------------------
    rw("glob_search_codebase", || {
        json_schema(vec![
            prop(
                "pattern",
                "string",
                "Glob pattern relative to the workspace root, e.g. `**/*.rs` or `src/**/main.*`.",
            ),
            prop_opt(
                "root",
                "string",
                "Absolute directory to search (defaults to the workspace root).",
            ),
            prop_opt(
                "respect_gitignore",
                "boolean",
                "Whether to skip paths ignored by git (default true).",
            ),
        ])
    }),
    rw("search_file_contents", || {
        json_schema(vec![
            prop("pattern", "string", "Regular expression to match against file contents, e.g. `fn connect_db` or `TODO.*fixme`."),
            prop_opt("include", "string", "Optional glob to restrict which files are searched (e.g. `src/**/*.rs`). Defaults to all files in the workspace."),
            prop_opt("root", "string", "Absolute directory to search (defaults to the workspace root)."),
            prop_opt("respect_gitignore", "boolean", "Whether to skip paths ignored by git (default true)."),
        ])
    }),
    rw("semantic_search_codebase", || {
        json_schema(vec![
            prop("query", "string", "Natural-language query describing what you're looking for, e.g. `where is the auth logic` or `how are timestamps formatted`. Results are ranked by code-aware relevance, not literal match."),
            prop_opt("include", "string", "Optional glob to restrict which files are indexed (e.g. `src/**/*.rs`). Defaults to all files in the workspace."),
            prop_opt("root", "string", "Absolute directory to search (defaults to the workspace root)."),
            prop_opt("respect_gitignore", "boolean", "Whether to skip paths ignored by git (default true)."),
            prop_opt("top_k", "integer", "How many ranked regions to return (default 10, max 25)."),
        ])
    }),
    rw("view_file_structure", || {
        json_schema(vec![
            prop(
                "path",
                "string",
                "Absolute path to the source file to parse.",
            ),
            prop_opt(
                "max_depth",
                "integer",
                "Maximum AST depth to scan for declarations (default 4).",
            ),
        ])
    }),
    rw("read_file_range", || {
        json_schema(vec![
            prop("path", "string", "Absolute path to the file."),
            prop("start_line", "integer", "First 1-based line to read."),
            prop(
                "end_line",
                "integer",
                "Last 1-based line to read (clamped to EOF).",
            ),
        ])
    }),
    rw("read_file_chars", || {
        json_schema(vec![
            prop("path", "string", "Absolute path to the text file."),
            prop_opt("offset", "integer", "0-based UTF-8 character offset to start reading from (default 0)."),
            prop_opt("limit", "integer", "Maximum characters to return (default 4000, max 24000). The result ends with <EOF> or a continuation hint."),
        ])
    }),
    rw("list_dir", || {
        json_schema(vec![
            prop_opt("path", "string", "Directory to list (absolute, or relative to the workspace root). Defaults to the workspace root."),
        ])
    }),
    rw("read_skill", || {
        json_schema(vec![
            prop("name", "string", "Name of an available skill (from the ## Skill instructions context section) to load in full. Use this when a skill was truncated to save context or you need its complete text before applying it."),
        ])
    }),
    rw("read_plan", || json_schema(vec![])),
    rw("get_scratchpad_folder", || json_schema(vec![])),
    rw("git_status", || {
        json_schema(vec![prop_opt(
            "git_status",
            "boolean",
            "Whether to return the porcelain status (default true).",
        )])
    }),
    rw("git_diff", || {
        json_schema(vec![prop_opt(
            "path",
            "string",
            "Optional path to scope the diff to a single file (relative to workspace root).",
        )])
    }),
    rw("git_blame", || {
        json_schema(vec![
            prop(
                "path",
                "string",
                "File to blame (relative to the workspace root).",
            ),
            prop_opt(
                "start_line",
                "integer",
                "First 1-based line of the range to blame.",
            ),
            prop_opt(
                "end_line",
                "integer",
                "Last 1-based line of the range to blame.",
            ),
        ])
    }),
    rw("git_pr_status", || json_schema(vec![])),
    rw("git_ci_status", || json_schema(vec![])),
    rw("summarize_changes", || json_schema(vec![])),
    rw("read_lints", || {
        json_schema(vec![prop(
            "path",
            "string",
            "File to lint (relative or absolute). Reports syntax errors for JS/TS/JSX/TSX, TODO/FIXME/HACK/XXX comment markers for any text file, empty catch blocks and stray `debugger` statements.",
        )])
    }),
    rw("view_repo_map", || {
        json_schema(vec![
            prop_opt(
                "top_n",
                "integer",
                "Number of most-relevant symbols/files to return (default 60, max 300).",
            ),
            prop_opt(
                "root",
                "string",
                "Optional directory to scope the map to (defaults to the workspace root).",
            ),
        ])
    }),
    rw("suggest_skills", || {
        json_schema(vec![
            prop(
                "prompt",
                "string",
                "The task description to match skills against (e.g. the user's request).",
            ),
            prop_opt(
                "path",
                "string",
                "Optional active file path; skills whose globs match it rank first.",
            ),
        ])
    }),
    // `calculate` is deterministic arithmetic — safe, but deliberately NOT in
    // the default-allow set (it was historically excluded); keep as-is.
    mutating("calculate", SubagentAccess::ReadOnly, || {
        json_schema(vec![prop(
            "expression",
            "string",
            "Arithmetic expression to evaluate: numbers, + - * / % ^, parentheses. Example: \"(2+3)*4\".",
        )])
    }),
    rw("attach_file", || {
        json_schema(vec![prop(
            "path",
            "string",
            "Absolute path of the text file to chunk + index for semantic search.",
        )])
    }),
    rw("search_attached_files", || {
        json_schema(vec![
            prop(
                "query",
                "string",
                "Natural-language query over the attached files.",
            ),
            prop_opt(
                "top_k",
                "integer",
                "How many chunks to return (1..20, default 5).",
            ),
        ])
    }),
    rw("tree_sitter_query", || {
        json_schema(vec![
            prop(
                "path",
                "string",
                "Absolute path to the source file to query (JS/TS/TSX/JSX supported).",
            ),
            prop(
                "query",
                "string",
                "A tree-sitter S-expression query pattern. Use @name captures to extract specific nodes. Example: `(function_declaration name: (identifier) @fn_name)`. Use `_.field` for field access, `(node_type)` for type matching, and alternatives like `(a|b)` for union patterns.",
            ),
            prop_opt(
                "max_results",
                "integer",
                "Maximum number of matches to return (default 50, max 200).",
            ),
        ])
    }),
    // Human-interaction tools: the user is always in the loop, so they are
    // default-allow on the parent; children can never reach them (ParentOnly).
    parent("ask_question", || {
        json_schema(vec![
            prop(
                "question",
                "string",
                "The question to ask the user. Be specific; include context so they can answer without scrolling back.",
            ),
            prop_opt(
                "choices",
                "array",
                "2-4 preset short answers shown as buttons. The user can always type a custom answer instead.",
            ),
        ])
    }),
    parent("send_to_user", || {
        json_schema(vec![prop(
            "message",
            "string",
            "A short message meant for the human user (status notes, decisions taken, heads-ups). Not a substitute for your final report.",
        )])
    }),
    rw("run_tests", || {
        json_schema(vec![
            prop_opt("command", "string", "Explicit test command. Omit to auto-detect (`npm test`, `cargo test`, …) from the workspace."),
        ])
    }),
    rw("get_todo_list", || json_schema(vec![])),
    rw("set_todo_list", || {
        json_schema(vec![
            prop("items", "array", "The full todo list as short imperative strings, in execution order. Replaces any previous list."),
        ])
    }),
    rw("mark_todo_item_done", || {
        json_schema(vec![prop(
            "item",
            "integer",
            "1-based index of the todo item to mark done.",
        )])
    }),
    rw("list_mcp_servers", || json_schema(vec![])),
    rw("detach_file", || {
        json_schema(vec![prop(
            "path",
            "string",
            "Path of a previously attached file to remove from the index.",
        )])
    }),
    // First-class subagents (P1-8): delegation itself is routine on the
    // parent; children obviously cannot delegate further.
    parent("task", || {
        json_schema(vec![
            prop_opt(
                "subagent_type",
                "string",
                "Specialist profile: `explore` (read-only codebase recon), `implement` (one focused change + verify), `review` (adversarial read-only review) or `debug` (reproduce + diagnose with tests/commands). Defaults to `explore`.",
            ),
            prop(
                "task",
                "string",
                "Single self-contained instruction for the subagent. It cannot see your conversation — include every file path, symbol and detail it needs. Finish yourself with a plain-text summary of its report; do not echo it verbatim.",
            ),
            prop_opt(
                "model_override",
                "string",
                "Optional model override for this subagent: a GGUF file path (local model) or `remote` (use the current remote provider). Enables architect mode — route planning to a large model and implementation to a smaller one.",
            ),
        ])
    }),

    // ---- mutating / build tools ------------------------------------------
    mutating("apply_file_diff", SubagentAccess::Implement, || {
        json_schema(vec![
            prop("path", "string", "Absolute path to the file to edit."),
            prop("diff", "string", "A SEARCH/REPLACE block:\n\n<diff>\n@@\nSEARCH:\n<existing lines>\nREPLACE:\n<new lines>\n</diff>\n\nBoth SEARCH and REPLACE are required and must be separated by exactly one blank line."),
        ])
    }),
    mutating("write_file", SubagentAccess::Implement, || {
        json_schema(vec![
            prop(
                "path",
                "string",
                "Absolute path of the file to write (must be inside the workspace).",
            ),
            prop("content", "string", "Full new file content."),
        ])
    }),
    mutating("create_folder", SubagentAccess::Implement, || {
        json_schema(vec![
            prop("path", "string", "Folder to create (mkdir -p semantics; absolute or relative to the workspace root). Depth is capped at 50 segments."),
        ])
    }),
    mutating("copy_file_or_folder", SubagentAccess::Implement, || {
        json_schema(vec![
            prop(
                "src",
                "string",
                "Source file or folder (copied recursively).",
            ),
            prop(
                "dst",
                "string",
                "Destination path; must not exist unless canOverwrite is true.",
            ),
            prop_opt(
                "can_overwrite",
                "boolean",
                "Replace an existing destination (default false).",
            ),
        ])
    }),
    mutating("move_file_or_folder", SubagentAccess::Implement, || {
        json_schema(vec![
            prop("src", "string", "Source file or folder to move/rename."),
            prop(
                "dst",
                "string",
                "Destination path; must not exist unless canOverwrite is true.",
            ),
            prop_opt(
                "can_overwrite",
                "boolean",
                "Replace an existing destination (default false).",
            ),
        ])
    }),
    mutating("delete_file_or_folder", SubagentAccess::ParentOnly, || {
        json_schema(vec![
            prop("path", "string", "File or folder to delete. Folders are removed recursively; the item goes to the OS Trash so it stays recoverable."),
        ])
    }),
    mutating("execute_terminal_command", SubagentAccess::Implement, || {
        json_schema(vec![
            prop(
                "command",
                "string",
                "Shell command to run. Avoid destructive or interactive commands.",
            ),
            prop_opt(
                "timeout_secs",
                "integer",
                "Timeout in seconds (1..300, default 30).",
            ),
            prop_opt(
                "cwd",
                "string",
                "Working directory for the command (defaults to workspace root).",
            ),
        ])
    }),
    mutating("run_python", SubagentAccess::Implement, || {
        json_schema(vec![
            prop(
                "code",
                "string",
                "The Python source code to run (a single script).",
            ),
            prop_opt(
                "timeout_secs",
                "integer",
                "Execution timeout in seconds (default 30, max 120).",
            ),
        ])
    }),
    mutating("run_javascript", SubagentAccess::Implement, || {
        json_schema(vec![
            prop("code", "string", "The JavaScript/TypeScript source to run (a single module). Deno preferred, Node.js >= 20 fallback."),
            prop_opt("timeout_secs", "integer", "Execution timeout in seconds (default 30, max 120)."),
        ])
    }),
    mutating("call_mcp_tool", SubagentAccess::Implement, || {
        json_schema(vec![
            prop_opt("server", "string", "Name of a configured MCP server from the catalog (see list_mcp_servers)."),
            prop_opt("server_bin", "string", "Ad-hoc executable path of an MCP server (stdio transport); use when no catalog entry exists."),
            prop_opt("server_args", "array", "Command-line arguments for the ad-hoc MCP server executable."),
            prop("tool", "string", "Tool name exposed by the MCP server."),
            prop_opt("arguments", "object", "JSON arguments for the tool call."),
            prop_opt("timeout_secs", "integer", "Timeout in seconds (default 30)."),
        ])
    }),
    mutating("add_mcp_server", SubagentAccess::ParentOnly, || {
        json_schema(vec![
            prop(
                "name",
                "string",
                "Short unique catalog name, e.g. \"playwright\".",
            ),
            prop(
                "bin",
                "string",
                "Executable path or PATH command for the stdio MCP server.",
            ),
            prop_opt(
                "args",
                "array",
                "Command-line arguments for the executable.",
            ),
        ])
    }),
    mutating("remove_mcp_server", SubagentAccess::ParentOnly, || {
        json_schema(vec![prop(
            "name",
            "string",
            "Catalog name of the server to remove.",
        )])
    }),
    mutating("download_file", SubagentAccess::ParentOnly, || {
        json_schema(vec![
            prop("url", "string", "Public http(s) URL of the file to download (max 100 MiB)."),
            prop("path", "string", "Destination path INSIDE the workspace; must not exist yet (absolute, or relative to the workspace root)."),
        ])
    }),

    // ---- git -----------
    mutating("git_commit", SubagentAccess::ParentOnly, || {
        json_schema(vec![prop(
            "message",
            "string",
            "Commit message describing the change.",
        )])
    }),
    mutating("git_checkpoint", SubagentAccess::ParentOnly, || {
        json_schema(vec![prop_opt(
            "message",
            "string",
            "Optional checkpoint label; auto-generates a message when omitted.",
        )])
    }),
    mutating("git_revert", SubagentAccess::ParentOnly, || {
        json_schema(vec![prop_opt(
            "commit",
            "string",
            "The checkpoint commit to revert to (defaults to the most recent checkpoint).",
        )])
    }),
    mutating("git_push", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop_opt("remote", "string", "Remote name (default `origin`)."),
            prop_opt(
                "branch",
                "string",
                "Branch to push (default: current branch).",
            ),
            prop_opt(
                "set_upstream",
                "boolean",
                "Push with `-u` to set upstream tracking — use for the first push of a new branch.",
            ),
        ])
    }),
    mutating("git_pull", SubagentAccess::Forbidden, || json_schema(vec![])),
    mutating("git_create_branch", SubagentAccess::Forbidden, || {
        json_schema(vec![prop(
            "name",
            "string",
            "New branch name; creates it AND switches to it (`git switch -c`). Refuses if it already exists.",
        )])
    }),
    mutating("create_pr", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop("title", "string", "Pull-request title."),
            prop_opt("body", "string", "Pull-request description (Markdown)."),
        ])
    }),

    // ---- plans / skills (parent-owned lifecycle) --------------------------
    mutating("create_plan", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop("title", "string", "Short title for the plan, e.g. `Refactor auth`."),
            prop_opt("goal", "string", "One sentence describing the overall goal the plan accomplishes."),
            prop("items", "array", "The ordered list of concrete steps to take. Each item should be a single self-contained directive the agent can execute."),
        ])
    }),
    mutating("update_plan", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop(
                "item",
                "integer",
                "1-based index of the plan item to update.",
            ),
            prop(
                "status",
                "string",
                "New status: `not_started`, `in_progress`, `completed` or `terminal`.",
            ),
            prop_opt(
                "details",
                "string",
                "Optional extra detail/result to record for the item (appended).",
            ),
        ])
    }),
    // execute_plan is intercepted by the orchestrator — parent only.
    mutating("execute_plan", SubagentAccess::ParentOnly, || {
        json_schema(vec![prop_opt(
            "execute_plan",
            "boolean",
            "Whether to begin executing the active plan (default true).",
        )])
    }),
    mutating("create_skill", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop("name", "string", "Short, descriptive skill name (e.g. `build-react-table`, `reproduce-bug`)."),
            prop_opt("description", "string", "One-line description of when to use this skill."),
            prop("content", "string", "Markdown body of the skill: the reusable procedure, checklist, or playbook you learned."),
        ])
    }),

    // ---- capabilities that were MISSING from the schema -------------------
    // Analyzer/reviewer as direct `problem` tools (read-only, never delegated
    // to children because they may spur a blocking LLM pass). Schemas are
    // required for the model to call them; previously absent.
    problem("analyze_bug", || {
        json_schema(vec![
            prop(
                "stack",
                "string",
                "The stack trace or error message to diagnose.",
            ),
            prop_opt(
                "path",
                "string",
                "Optional explicit file path to focus the analysis on when the trace has no usable `file:line` references.",
            ),
        ])
    }),
    problem("review_code", || {
        json_schema(vec![
            prop_opt(
                "path",
                "string",
                "File path to review (absolute, or relative to the workspace root). Exactly one of `path` or `diff` should be given.",
            ),
            prop_opt(
                "diff",
                "string",
                "A unified diff (as produced by `git diff`) to review; only its added lines are analyzed. Exactly one of `path` or `diff` should be given.",
            ),
        ])
    }),
    problem("browse_web", || {
        json_schema(vec![
            prop("url", "string", "Public http(s) URL of the page to fetch. Private/loopback hosts and embedded credentials are rejected."),
            prop_opt(
                "action",
                "string",
                "What to do with the page: `fetch` (extract readable text, default) or `screenshot` (requires a bundled headless browser).",
            ),
        ])
    }),

    // ---- everything else (Forbidden for children by omission) ------------
    mutating("transcribe_audio", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop(
                "path",
                "string",
                "Absolute path of an audio/video file (wav, mp3, m4a, webm…).",
            ),
            prop_opt(
                "language",
                "string",
                "ISO language hint, e.g. \"en\" or \"de\" (default: auto-detect).",
            ),
        ])
    }),
    mutating("web_search", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop("query", "string", "The web search query."),
            prop_opt(
                "max_results",
                "integer",
                "How many results to return (default 8, max 10).",
            ),
        ])
    }),
    mutating("web_extract", SubagentAccess::Forbidden, || {
        json_schema(vec![
            prop("url", "string", "Public http(s) URL of the page to fetch. Private/loopback hosts and embedded credentials are rejected."),
        ])
    }),
];

impl ToolMeta {
    pub fn get(name: &str) -> Option<&'static ToolMeta> {
        TOOLS.iter().find(|m| m.name == name)
    }

    /// Parent agents may always call every registered tool.
    pub fn parent_allowed(&self) -> bool {
        true
    }
}

/// The JSON schema map advertised to the model — derived entirely from the
/// registry so a tool can never exist in one list and not the other.
pub fn tool_schemas() -> HashMap<&'static str, Value> {
    TOOLS.iter().map(|m| (m.name, (m.schema)())).collect()
}

/// Is this tool safe to auto-allow (skip the approval gate) by default?
pub fn is_read_only(name: &str) -> bool {
    ToolMeta::get(name).map(|m| m.read_only).unwrap_or(false)
}

/// The canonical set of every registered tool name (used by the drift guard).
pub fn all_names() -> Vec<&'static str> {
    TOOLS.iter().map(|m| m.name).collect()
}

/// Tool names a delegated subagent of `profile` may call.
///
/// Derived straight from the registry so `tool_allowed` can never disagree
/// with the metadata. `profile` is lowercased by the caller.
pub fn subagent_allowed(profile: &str) -> Vec<&'static str> {
    let profile = profile.trim().to_ascii_lowercase();
    let implement = matches!(profile.as_str(), "implement");
    TOOLS
        .iter()
        .filter(|m| match (m.delegation, implement) {
            (SubagentAccess::ParentOnly, _) => false,
            (SubagentAccess::Forbidden, _) => false,
            (SubagentAccess::ReadOnly, _) => true,
            (SubagentAccess::Implement, true) => true,
            (SubagentAccess::Implement, false) => false,
        })
        .map(|m| m.name)
        .collect()
}

/// Is this tool reserved for the parent agent (never callable by a child)?
pub fn is_parent_only(name: &str) -> bool {
    ToolMeta::get(name)
        .map(|m| m.delegation == SubagentAccess::ParentOnly)
        .unwrap_or(false)
}

/// Names in the parent-only set (`CHILD_NEVER`) — used by tests.
pub fn parent_only_names() -> Vec<&'static str> {
    TOOLS
        .iter()
        .filter(|m| m.delegation == SubagentAccess::ParentOnly)
        .map(|m| m.name)
        .collect()
}

/// Prove the registry is internally consistent and covers every name produced
/// by the dispatcher. Called by `core::test_registry_matches_dispatcher`.
pub fn validate(dispatcher_names: &[&str]) -> Result<(), String> {
    let mut registered: Vec<&'static str> = all_names();
    registered.sort_unstable();
    let mut dispatched: Vec<&str> = dispatcher_names.to_vec();
    dispatched.sort_unstable();
    dispatched.dedup();

    let missing_from_registry: Vec<&str> = dispatched
        .iter()
        .filter(|n| !registered.iter().any(|r| r == *n))
        .cloned()
        .collect();
    if !missing_from_registry.is_empty() {
        return Err(format!(
            "tools dispatched but missing from registry: {}",
            missing_from_registry.join(", ")
        ));
    }

    let extra_in_registry: Vec<&str> = registered
        .iter()
        .filter(|r| !dispatched.iter().any(|d| d == *r))
        .map(|r| *r)
        .collect();
    if !extra_in_registry.is_empty() {
        return Err(format!(
            "registry names with no dispatcher arm: {}",
            extra_in_registry.join(", ")
        ));
    }

    for meta in TOOLS {
        if meta.name.trim().is_empty() {
            return Err("registry contains an empty tool name".into());
        }
        let schema = (meta.schema)();
        if !schema.is_object() {
            return Err(format!("`{}` has a malformed schema", meta.name));
        }
        if schema.get("properties").and_then(|v| v.as_object()).is_none() {
            return Err(format!("`{}` schema has no `properties` object", meta.name));
        }
    }
    Ok(())
}

fn json_schema(props: Vec<Value>) -> Value {
    let mut required = Vec::new();
    let mut object = serde_json::Map::new();
    for p in props {
        let mut p_obj = p.as_object().unwrap().clone();
        let name = p_obj.get("name").unwrap().as_str().unwrap().to_string();
        let is_optional = p_obj
            .get("optional")
            .map(|o| o.as_bool().unwrap_or(false))
            .unwrap_or(false);
        p_obj.remove("optional");
        p_obj.remove("name");
        if !is_optional {
            required.push(name.clone());
        }
        object.insert(name, Value::Object(p_obj));
    }
    serde_json::json!({
        "type": "object",
        "properties": object,
        "required": required,
        "additionalProperties": false
    })
}

fn prop(name: &str, ty: &str, desc: &str) -> Value {
    serde_json::json!({ "name": name, "type": ty, "description": desc })
}

fn prop_opt(name: &str, ty: &str, desc: &str) -> Value {
    serde_json::json!({ "name": name, "type": ty, "description": desc, "optional": true })
}